#!/bin/sh

## This script creates the fltube.conf file at user HOME (if not exists)
## and install yt-dlp at $HOME/.local/bin if not reachable from PATH...

nonroot_user="$(cat /etc/sysconfig/tcuser)"
su "$nonroot_user" <<EOF
FLTUBE_USER_CONFIGDIR=/home/\$nonroot_user/.config/fltube
YTDLP_USER_CONFIGDIR=/home/\$nonroot_user/.config/yt-dlp
if [ ! -f "\$FLTUBE_USER_CONFIGDIR"/fltube.conf ]; then
    [ ! -d "\$FLTUBE_USER_CONFIGDIR" ] && mkdir -p "\$FLTUBE_USER_CONFIGDIR"
	cp /tmp/tcloop/fltube/usr/local/etc/fltube/fltube.conf "\$FLTUBE_USER_CONFIGDIR"
fi

if [ ! -f "\$YTDLP_USER_CONFIGDIR"/config ]; then
    [ ! -d "\$YTDLP_USER_CONFIGDIR" ] && mkdir -p "\$YTDLP_USER_CONFIGDIR"
	echo "Creating user configuration file for 'yt-dlp' at \$YTDLP_USER_CONFIGDIR."
	cp /tmp/yt-dlp_config "\$YTDLP_USER_CONFIGDIR/config"
fi

command -v yt-dlp >/dev/null 2>&1 || { /tmp/tcloop/fltube/usr/local/bin/install_yt-dlp.sh -y; }
EOF
