/*
 * Copyright (C) 2025 - FLtube
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License, version 3, as published
 * by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 */
// generated by Fast Light User Interface Designer (fluid) version 1.0404

#ifndef FLTube_View_h
#define FLTube_View_h
#include <FL/Fl.H>
#ifndef GETTEXT_MACROS_H
#define GETTEXT_MACROS_H
#define _(String) gettext(String)
#define ng_(SINGULAR, PLURAL, COUNT) ngettext(SINGULAR, PLURAL, COUNT)
#endif
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Choice.H>

class FLTubeMainWindow : public Fl_Double_Window {
  void _FLTubeMainWindow();
public:
  FLTubeMainWindow(int X, int Y, int W, int H, const char *L = 0);
  FLTubeMainWindow(int W, int H, const char *L = 0);
  FLTubeMainWindow();
  Fl_Button *about_bttn;
  Fl_Tabs *central_tabs;
  Fl_Group *searchbox_tab;
  Fl_Input *search_term_or_url;
  Fl_Button *do_search_bttn;
  Fl_Group *videolists_tab;
  Fl_Choice *videolist_selector;
  Fl_Group *search_result_selectors;
  Fl_Group *pagination_controls;
  Fl_Button *previous_results_bttn;
  Fl_Button *next_results_bttn;
};
#include <FL/Fl_Box.H>

class VideoInfo : public Fl_Group {
public:
  VideoInfo(int X, int Y, int W, int H, const char *L = 0);
  Fl_Button *thumbnail;
  Fl_Box *views_spectators;
  Fl_Box *is_live_image;
  Fl_Box *already_viewed_icon;
  Fl_Button *like_icon_bttn;
  Fl_Box *title;
  Fl_Box *duration;
  Fl_Box *uploadDate;
  Fl_Button *userUploader;
};

class TinyMessageWindow : public Fl_Double_Window {
  void _TinyMessageWindow();
public:
  TinyMessageWindow(int X, int Y, int W, int H, const char *L = 0);
  TinyMessageWindow(int W, int H, const char *L = 0);
  TinyMessageWindow();
  Fl_Box *error_label;
  Fl_Button *close_bttn;
};
#include <FL/Fl_Check_Button.H>

class TinyChoiceWindow : public Fl_Double_Window {
  void _TinyChoiceWindow();
public:
  TinyChoiceWindow(int X, int Y, int W, int H, const char *L = 0);
  TinyChoiceWindow(int W, int H, const char *L = 0);
  TinyChoiceWindow();
  Fl_Box *choice_label;
  Fl_Button *accept_bttn;
  Fl_Button *cancel_bttn;
  Fl_Check_Button *warnme_again_check;
};
#include <FL/Fl_Text_Display.H>

class HelpFLTubeWindow : public Fl_Double_Window {
  void _HelpFLTubeWindow();
public:
  HelpFLTubeWindow(int X, int Y, int W, int H, const char *L = 0);
  HelpFLTubeWindow(int W, int H, const char *L = 0);
  HelpFLTubeWindow();
  Fl_Box *hlp_fltube_img;
  Fl_Box *hlp_app_name;
  Fl_Box *about_version;
  Fl_Button *hlp_fltk_link;
  Fl_Button *hlp_source_code;
  Fl_Button *hlp_ytdlp_link;
  Fl_Button *hlp_cpp_link;
  Fl_Tabs *help_info_tabs;
  Fl_Group *howtouse_tab;
  Fl_Text_Display *howtouse_txt;
  Fl_Group *shortcuts_tab;
  Fl_Text_Display *shortcuts_txt;
  Fl_Group *config_tab;
  Fl_Text_Display *config_txt;
  Fl_Group *authors_tab;
  Fl_Text_Display *authors_txt;
};
#endif
