/*
 * Copyright (C) 2025 - FLtube
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License, version 3, as published
 * by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 */
// generated by Fast Light User Interface Designer (fluid) version 1.0311

#ifndef FLTube_View_h
#define FLTube_View_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>

class FLTubeMainWindow : public Fl_Double_Window {
  void _FLTubeMainWindow();
public:
  FLTubeMainWindow(int X, int Y, int W, int H, const char *L = 0);
  FLTubeMainWindow(int W, int H, const char *L = 0);
  FLTubeMainWindow();
  Fl_Input *search_term_or_url;
  Fl_Button *do_search_bttn;
  Fl_Group *search_result_selectors;
  Fl_Text_Display *output_text_display;
  Fl_Group *pagination_controls;
  Fl_Button *previous_results_bttn;
  Fl_Button *next_results_bttn;
};
#include <FL/Fl_Box.H>

class VideoInfo : public Fl_Group {
public:
  VideoInfo(int X, int Y, int W, int H, const char *L = 0);
  Fl_Box *thumbnail;
  Fl_Box *title;
  Fl_Box *duration;
  Fl_Box *uploadDate;
  Fl_Button *userUploader;
  Fl_Button *d240;
  Fl_Button *d360;
  Fl_Button *d480;
  Fl_Button *d720;
  Fl_Button *d1080;
};

class TinyMessageWindow : public Fl_Double_Window {
  void _TinyMessageWindow();
public:
  TinyMessageWindow(int X, int Y, int W, int H, const char *L = 0);
  TinyMessageWindow(int W, int H, const char *L = 0);
  TinyMessageWindow();
  Fl_Box *error_label;
  Fl_Button *close_bttn;
};
#endif
