/*
 * Copyright (C) 2025 - FLtube
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License, version 3, as published
 * by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 */
// generated by Fast Light User Interface Designer (fluid) version 1.0404

#include "../include/FLTube_View.h"
#include <libintl.h>
#ifndef gettext_noop
#  define gettext_noop(text) text
#endif
#ifndef GETTEXT_MACROS_H
#endif

FLTubeMainWindow::FLTubeMainWindow(int X, int Y, int W, int H, const char *L) :
  Fl_Double_Window(X, Y, W, H, L)
{
  _FLTubeMainWindow();
}

FLTubeMainWindow::FLTubeMainWindow(int W, int H, const char *L) :
  Fl_Double_Window(0, 0, W, H, L)
{
  clear_flag(16);
  _FLTubeMainWindow();
}

FLTubeMainWindow::FLTubeMainWindow() :
  Fl_Double_Window(0, 0, 593, 540, "FLTube")
{
  clear_flag(16);
  _FLTubeMainWindow();
}

void FLTubeMainWindow::_FLTubeMainWindow() {
  this->box(FL_FLAT_BOX);
  this->color(FL_BACKGROUND_COLOR);
  this->selection_color(FL_BACKGROUND_COLOR);
  this->labeltype(FL_NO_LABEL);
  this->labelfont(0);
  this->labelsize(14);
  this->labelcolor(FL_FOREGROUND_COLOR);
  this->align(Fl_Align(FL_ALIGN_TOP));
  this->when(FL_WHEN_RELEASE);
  { Fl_Group* o = new Fl_Group(10, 35, 575, 85, _("Search box:"));
    o->box(FL_UP_FRAME);
    o->labelfont(1);
    o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    { search_term_or_url = new Fl_Input(46, 59, 512, 24, _("Term or URL"));
      search_term_or_url->tooltip(_("Enter a search term for search or a valid Youtube URL."));
      search_term_or_url->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Input* search_term_or_url
    { do_search_bttn = new Fl_Button(227, 88, 150, 22, _("Go &search!"));
      do_search_bttn->tooltip(_("If search by URL, it must be a complete one (i.e. https://youtu.be/12345)..."));
      do_search_bttn->user_data((void*)(search_term_or_url));
    } // Fl_Button* do_search_bttn
    o->end();
  } // Fl_Group* o
  { search_result_selectors = new Fl_Group(10, 126, 575, 380);
    search_result_selectors->box(FL_THIN_UP_BOX);
    search_result_selectors->end();
  } // Fl_Group* search_result_selectors
  { pagination_controls = new Fl_Group(9, 508, 577, 30);
    { previous_results_bttn = new Fl_Button(10, 510, 135, 23, _("<&Previous"));
      previous_results_bttn->tooltip(_("Get previous results of current search results set."));
    } // Fl_Button* previous_results_bttn
    { next_results_bttn = new Fl_Button(450, 510, 135, 23, _("&Next>"));
      next_results_bttn->tooltip(_("Get following results of current search results set."));
    } // Fl_Button* next_results_bttn
    pagination_controls->end();
  } // Fl_Group* pagination_controls
  { about_bttn = new Fl_Button(521, 9, 64, 22, _("Help"));
    about_bttn->tooltip(_("Show info about this application and some help of how to use it."));
  } // Fl_Button* about_bttn
  end();
}

VideoInfo::VideoInfo(int X, int Y, int W, int H, const char *L) :
  Fl_Group(0, 0, W, H, L)
{
  { thumbnail = new Fl_Button(6, 5, 95, 80);
    thumbnail->tooltip(_("Click to stream the video (preview it)..."));
  } // Fl_Button* thumbnail
  { views_spectators = new Fl_Box(105, 43, 110, 20);
    views_spectators->tooltip(_("Total video views, or if live current count of concurrent spectators."));
    views_spectators->align(Fl_Align(356|FL_ALIGN_INSIDE));
  } // Fl_Box* views_spectators
  { is_live_image = new Fl_Box(220, 43, 40, 20);
    is_live_image->tooltip(_("The video is live."));
    is_live_image->align(Fl_Align(288));
    is_live_image->hide();
  } // Fl_Box* is_live_image
  { already_viewed_icon = new Fl_Box(265, 43, 20, 20);
    already_viewed_icon->tooltip(_("You have view this video in the past."));
    already_viewed_icon->align(Fl_Align(288));
    already_viewed_icon->hide();
  } // Fl_Box* already_viewed_icon
  { title = new Fl_Box(105, 6, 450, 37);
    title->labelfont(1);
    title->align(Fl_Align(197|FL_ALIGN_INSIDE));
  } // Fl_Box* title
  { duration = new Fl_Box(105, 65, 70, 20);
    duration->tooltip(_("Duration expressed as H:MM:SS."));
    duration->labelfont(2);
    duration->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
  } // Fl_Box* duration
  { uploadDate = new Fl_Box(190, 65, 95, 20);
    uploadDate->tooltip(_("Video upload date."));
    uploadDate->labelfont(2);
    uploadDate->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
  } // Fl_Box* uploadDate
  { userUploader = new Fl_Button(295, 65, 260, 20);
    userUploader->tooltip(_("Click to list all channel\'s video."));
    userUploader->labelfont(2);
    userUploader->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
  } // Fl_Button* userUploader
  end();
  position(X, Y);
}

TinyMessageWindow::TinyMessageWindow(int X, int Y, int W, int H, const char *L) :
  Fl_Double_Window(X, Y, W, H, L)
{
  _TinyMessageWindow();
}

TinyMessageWindow::TinyMessageWindow(int W, int H, const char *L) :
  Fl_Double_Window(0, 0, W, H, L)
{
  clear_flag(16);
  _TinyMessageWindow();
}

TinyMessageWindow::TinyMessageWindow() :
  Fl_Double_Window(0, 0, 649, 100, "Error")
{
  clear_flag(16);
  _TinyMessageWindow();
}

void TinyMessageWindow::_TinyMessageWindow() {
  this->box(FL_FLAT_BOX);
  this->color(FL_BACKGROUND_COLOR);
  this->selection_color(FL_BACKGROUND_COLOR);
  this->labeltype(FL_NO_LABEL);
  this->labelfont(0);
  this->labelsize(14);
  this->labelcolor(FL_FOREGROUND_COLOR);
  this->align(Fl_Align(FL_ALIGN_TOP));
  this->when(FL_WHEN_RELEASE);
  { error_label = new Fl_Box(30, 15, 590, 45);
    error_label->align(Fl_Align(FL_ALIGN_WRAP));
  } // Fl_Box* error_label
  { close_bttn = new Fl_Button(267, 70, 115, 25, _("Close and exit"));
    close_bttn->shortcut(FL_ALT|'c');
  } // Fl_Button* close_bttn
  set_modal();
  end();
}

TinyChoiceWindow::TinyChoiceWindow(int X, int Y, int W, int H, const char *L) :
  Fl_Double_Window(X, Y, W, H, L)
{
  _TinyChoiceWindow();
}

TinyChoiceWindow::TinyChoiceWindow(int W, int H, const char *L) :
  Fl_Double_Window(0, 0, W, H, L)
{
  clear_flag(16);
  _TinyChoiceWindow();
}

TinyChoiceWindow::TinyChoiceWindow() :
  Fl_Double_Window(0, 0, 649, 118, "Warn")
{
  clear_flag(16);
  _TinyChoiceWindow();
}

void TinyChoiceWindow::_TinyChoiceWindow() {
  this->box(FL_FLAT_BOX);
  this->color(FL_BACKGROUND_COLOR);
  this->selection_color(FL_BACKGROUND_COLOR);
  this->labeltype(FL_NO_LABEL);
  this->labelfont(0);
  this->labelsize(14);
  this->labelcolor(FL_FOREGROUND_COLOR);
  this->align(Fl_Align(FL_ALIGN_TOP));
  this->when(FL_WHEN_RELEASE);
  { choice_label = new Fl_Box(30, 15, 590, 45);
    choice_label->align(Fl_Align(FL_ALIGN_WRAP));
  } // Fl_Box* choice_label
  { accept_bttn = new Fl_Button(180, 85, 115, 25, _("Accept"));
    accept_bttn->shortcut(FL_ALT|'a');
  } // Fl_Button* accept_bttn
  { cancel_bttn = new Fl_Button(334, 85, 115, 25, _("Cancel"));
    cancel_bttn->shortcut(FL_ALT|'c');
  } // Fl_Button* cancel_bttn
  { warnme_again_check = new Fl_Check_Button(30, 60, 590, 20, _("Don\'t warn me again and ACCEPT always."));
    warnme_again_check->tooltip(_("Check if don\'t want to be warn again, assuming all risks."));
    warnme_again_check->down_box(FL_DOWN_BOX);
    warnme_again_check->labelfont(2);
    warnme_again_check->labelsize(12);
  } // Fl_Check_Button* warnme_again_check
  set_modal();
  end();
}

HelpFLTubeWindow::HelpFLTubeWindow(int X, int Y, int W, int H, const char *L) :
  Fl_Double_Window(X, Y, W, H, L)
{
  _HelpFLTubeWindow();
}

HelpFLTubeWindow::HelpFLTubeWindow(int W, int H, const char *L) :
  Fl_Double_Window(0, 0, W, H, L)
{
  clear_flag(16);
  _HelpFLTubeWindow();
}

HelpFLTubeWindow::HelpFLTubeWindow() :
  Fl_Double_Window(0, 0, 480, 352, "FLTube Help")
{
  clear_flag(16);
  _HelpFLTubeWindow();
}

void HelpFLTubeWindow::_HelpFLTubeWindow() {
  this->box(FL_FLAT_BOX);
  this->color(FL_BACKGROUND_COLOR);
  this->selection_color(FL_BACKGROUND_COLOR);
  this->labeltype(FL_NO_LABEL);
  this->labelfont(0);
  this->labelsize(14);
  this->labelcolor(FL_FOREGROUND_COLOR);
  this->align(Fl_Align(FL_ALIGN_TOP));
  this->when(FL_WHEN_RELEASE);
  { Fl_Group* o = new Fl_Group(15, 14, 448, 144);
    { hlp_fltube_img = new Fl_Box(15, 21, 128, 128);
    } // Fl_Box* hlp_fltube_img
    { hlp_app_name = new Fl_Box(153, 14, 310, 24, _("FLTube"));
      hlp_app_name->labelfont(1);
      hlp_app_name->labelsize(20);
      hlp_app_name->labelcolor(FL_GRAY0);
      hlp_app_name->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* hlp_app_name
    { about_version = new Fl_Box(153, 38, 302, 19, _("Version x.y.z"));
      about_version->labelfont(2);
      about_version->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* about_version
    { Fl_Box* o = new Fl_Box(153, 57, 310, 21, _("Watch YouTube videos in your very old PC."));
      o->labelsize(15);
      o->align(Fl_Align(133|FL_ALIGN_INSIDE));
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(153, 86, 114, 24, _("Technologies:"));
      o->align(Fl_Align(FL_ALIGN_BOTTOM_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(153, 110, 110, 20, _("Source code at:"));
      o->align(Fl_Align(FL_ALIGN_BOTTOM_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(153, 132, 309, 18, _("Licensed under GNU GPL v3.0."));
      o->align(Fl_Align(FL_ALIGN_BOTTOM_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* o
    { hlp_fltk_link = new Fl_Button(271, 87, 48, 23, _("FLTK"));
      hlp_fltk_link->tooltip(_("Click to open FLTK official website."));
      hlp_fltk_link->box(FL_NO_BOX);
      hlp_fltk_link->color(FL_LIGHT1);
      hlp_fltk_link->labelcolor((Fl_Color)137);
      hlp_fltk_link->align(Fl_Align(FL_ALIGN_BOTTOM_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Button* hlp_fltk_link
    { hlp_source_code = new Fl_Button(269, 110, 180, 19, _("gitlab.com/facuA/fltube"));
      hlp_source_code->tooltip(_("Click to open FLTube repository."));
      hlp_source_code->box(FL_NO_BOX);
      hlp_source_code->color(FL_LIGHT1);
      hlp_source_code->labelcolor((Fl_Color)137);
      hlp_source_code->align(Fl_Align(FL_ALIGN_BOTTOM_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Button* hlp_source_code
    { hlp_ytdlp_link = new Fl_Button(333, 88, 52, 22, _("yt-dlp"));
      hlp_ytdlp_link->tooltip(_("Click to open yt-dlp official website."));
      hlp_ytdlp_link->box(FL_NO_BOX);
      hlp_ytdlp_link->labelcolor((Fl_Color)137);
      hlp_ytdlp_link->align(Fl_Align(FL_ALIGN_BOTTOM_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Button* hlp_ytdlp_link
    { hlp_cpp_link = new Fl_Button(399, 87, 38, 23, _("C++"));
      hlp_cpp_link->tooltip(_("Click to open C++ official website."));
      hlp_cpp_link->box(FL_NO_BOX);
      hlp_cpp_link->labelcolor((Fl_Color)137);
      hlp_cpp_link->align(Fl_Align(FL_ALIGN_BOTTOM_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Button* hlp_cpp_link
    o->end();
  } // Fl_Group* o
  { help_info_tabs = new Fl_Tabs(15, 158, 450, 183);
    { howtouse_tab = new Fl_Group(15, 183, 450, 158, _("How to use"));
      howtouse_tab->selection_color(FL_DARK1);
      howtouse_tab->labelfont(1);
      { howtouse_txt = new Fl_Text_Display(19, 189, 442, 148);
        howtouse_txt->box(FL_NO_BOX);
        howtouse_txt->color(FL_BACKGROUND_COLOR);
        howtouse_txt->align(Fl_Align(129));
      } // Fl_Text_Display* howtouse_txt
      howtouse_tab->end();
    } // Fl_Group* howtouse_tab
    { shortcuts_tab = new Fl_Group(15, 183, 450, 158, _("Shortcuts"));
      shortcuts_tab->selection_color(FL_DARK1);
      shortcuts_tab->labelfont(1);
      shortcuts_tab->hide();
      { shortcuts_txt = new Fl_Text_Display(19, 189, 442, 148);
        shortcuts_txt->box(FL_NO_BOX);
        shortcuts_txt->color(FL_BACKGROUND_COLOR);
        shortcuts_txt->align(Fl_Align(129));
      } // Fl_Text_Display* shortcuts_txt
      shortcuts_tab->end();
    } // Fl_Group* shortcuts_tab
    { config_tab = new Fl_Group(15, 183, 450, 158, _("Configuration"));
      config_tab->selection_color(FL_DARK1);
      config_tab->labelfont(1);
      config_tab->hide();
      { config_txt = new Fl_Text_Display(19, 189, 442, 148);
        config_txt->box(FL_NO_BOX);
        config_txt->color(FL_BACKGROUND_COLOR);
        config_txt->align(Fl_Align(129));
      } // Fl_Text_Display* config_txt
      config_tab->end();
    } // Fl_Group* config_tab
    { authors_tab = new Fl_Group(15, 183, 450, 158, _("Authors"));
      authors_tab->selection_color(FL_DARK1);
      authors_tab->labelfont(1);
      authors_tab->hide();
      { authors_txt = new Fl_Text_Display(19, 189, 442, 148);
        authors_txt->box(FL_NO_BOX);
        authors_txt->color(FL_BACKGROUND_COLOR);
        authors_txt->align(Fl_Align(129));
      } // Fl_Text_Display* authors_txt
      authors_tab->end();
    } // Fl_Group* authors_tab
    help_info_tabs->end();
  } // Fl_Tabs* help_info_tabs
  set_modal();
  end();
}
